### ISSUE TITLE
Don't pollute the Vue instance

### ISSUE THREAD

**Issue by adi518** [y-nk/vue-fragments#1]
Define the directive as a module:
```js
export default {
  inserted(element) {
    const fragment = document.createDocumentFragment()
    Array.from(element.childNodes).forEach(child => fragment.appendChild(child))
    element.parentNode.insertBefore(fragment, element)
    element.parentNode.removeChild(element)
  }
}
```
Then the component, so there's no coupling and more reusability :
```js
import directive from './directive'

export default {
  name: 'v-fragment',
  directives: { fragment: directive },
  template: `<div v-fragment><slot /></div>`
}
```
Then, export the whole thing:
```js
export { default as VFragment } from './Fragment'
export { default as directive } from './directive'
```
Usage:
```vue
<template>
  <div id="app">
    <v-fragment>
      <span>It</span> 
      <span>Actually</span> 
      <span>Works</span> 
    </v-fragment>
  </div>
</template>

<script>
import { VFragment } from 'vue-fragments'

export default {
  components: { VFragment }
}
</script>
```
And don't forget, for consumers to use it, you have to bundle it so it gets transpiled to ES5. Also if `vue-<component-name>` is already taken, I just add `-component`, so: `vue-fragment-component`.

**Comment by y-nk** [comment]
thank you for the comments and feedback. I honestly didn't know you could suggest a directive this way... if so, it would certainly look like that. I made changes as you suggested and decided to code directly in ES5 since the codebase is so small, there's no real need for bundling... I  also decided to keep the plugin entry point as an _auto-magic thing_ for convenience, but people can now choose to import as you suggested (which i will use from now on).

**Comment by y-nk** [comment]
thank you for the comments and feedback. I honestly didn't know you could suggest a directive this way... if so, it would certainly look like that. I made changes as you suggested and decided to code directly in ES5 since the codebase is so small and will work on bundling. I also decided to keep the plugin entry point as an auto-magic thing for convenience, but people can now choose to import as you suggested (which i will use from now on).

**Comment by rupesh-terase** [comment]
this also do not work with n level nesting 

```
<template>
    <v-fragment>
        <component v-for="(child, index) in nestedcomp" :key="index" :id="child.id" :is="child.component" v-bind="child.props.options">
            <app-renderer v-if="child.childrens.length > 0" :nestedcomp="child.childrens" />
        </component>
    </v-fragment>
</template>

<script>
import { VFragment } from '../utils/fragment';

export default {
    components: { VFragment },
    //name: 'childrender',
    props: ['nestedcomp'],
    methods: {

    }
}

</script>
```
I have following case 

-  component0  (0 level works) primary component have root element
-- component1 (1 level works) above code starts executing
--- component2 (2 level works) above code starts executing
-- component3 (1 level with component1) fails the case.

**Comment by rupesh-terase** [comment]
```
[Vue warn]: Error in directive fragment update hook: "TypeError: element.parentNode is null"

found in

---> <VFragment>

From this what i understand is child nodes do not know about updated parents, is that correct?

Also one more point to note that if component is already loaded then updated(directive) event gets fired instead of inserted(directive) event, It fires for all elements which has v-fragment attached .

**Comment by y-nk** [comment]
@rupesh-terase i think this is quite separate issue. could you open a new one ? i will sure look into it.
